composer.json

There is a tagged release of adoy/oauth2.
Would be nice if this project used that (both more stable and easier to set up).

Use a tagged release of adoy/oauth2

---

README.md

As #15 got in, the message about having to manually adding the dependency for adoy/oauth2 can be removed from the readme.

Removed note about unstable dependency from README

---

src/Auth0/Login/Middleware/Auth0JWTMiddleware.php

See http://laravel.com/docs/master/upgrade#upgrade-5.1.0
The middleware contract is deprecated in 5.1 and will be removed in 5.2 (due december 2015).

Middleware contract has been deprecated in 5.1

---

src/Auth0/Login/LaravelSessionStore.php

The Auth0 SDK checks for null values when determining if a user exists.
https://github.com/auth0/auth0-PHP/blob/2.1.2/src/Auth0.php#L276
If the default value for getting a value out of the session store is set to false
```php
if ($this->user === null) {
$this->exchangeCode();
}
```
will never get executed and the user will not be logged in.

Auth0 SDK checks for null values instead of false

---

src/Auth0/Login/Auth0JWTUser.php

Laravel 5.2 introduced the `getAuthIdentifierName` abstract function in its Authenticatable contract, throwing an error if `AuthJWTUser` is used to authenticate.
`Auth0JWTUser` just needs its own version of this function to work properly.

Conform to 5.2's Authenticatable contract

---

src/Auth0/Login/Auth0Service.php
src/controllers/Auth0Controller.php

This adds functionality to enable the "remember me" function in laravel.
As with the `onLogin()` method hook to persist or retrieve the user from the local DB, this can be used with the `Auth0` facade.
```
\Auth0::rememberUser(true);
```

Remember user

---

src/Auth0/Login/LoginServiceProvider.php

Now the events have a different name. We are listening to "auth.logout" but now it's named "Illuminate\Auth\Events\Logout"
See https://laravel.com/docs/5.2/upgrade
Please check if we are listening to more events and fix them

Fix for Laravel 5.2

---

README.md
src/Auth0/Login/Auth0Service.php
src/config/config.php
src/facade/Auth0.php

Add default scope, general fixes

---

src/Auth0/Login/Auth0Service.php
src/config/config.php

For those unfortunate enough to be behind a proxy, verifying tokens fails as the client domain address cannot be reached (e.g. client-domain-name.eu.auth0.com)
Adding connection options to the config allows users of this repo to specify additional options on the guzzle plugin and therefore allow traffic to pass through the proxy and JWT tokens to be verified.
An example configuration:
`     
'guzzle_options' => [ 'curl' => [CURLOPT_PROXY => 'your-proxy-address.com',
CURLOPT_SSL_VERIFYPEER => true,
CURLOPT_PROXYPORT => '8080',
CURLOPT_PROXYUSERPWD => 'username:password']],
`
Thanks

Added guzzle options to config to allow for connection options

---

composer.json
src/Auth0/Login/Auth0Service.php

Utilise Auth0->Login to ensure state validation

---

src/config/config.php

Improved defaults based on new clients, use env() where appropriate.

Change default settings file

---

src/controllers/Auth0Controller.php

Replaces gendered references to users with a neutral 'them'.

Make code comments gender neutral

---

CHANGELOG.md
README.md

Fix README and CHANGELOG

---

src/Auth0/Login/LoginServiceProvider.php

Since the Auth0Service is registered under the name auth0 in the app container it doesn't load the instance when you use it in a constructor, since it is used in the authentication provider like this:
```php
<?php
// ...
/**
* Service that provides an Auth0\LaravelAuth0\Auth0User stored in the session. This User provider
* should be used when you don't want to persist the entity.
*/
class Auth0UserProvider implements UserProvider
{
protected $userRepository;
protected $auth0;
/**
* Auth0UserProvider constructor.
*
* @param Auth0UserRepository       $userRepository
* @param \Auth0\Login\Auth0Service $auth0
*/
public function __construct(Auth0UserRepository $userRepository, Auth0Service $auth0)
{
$this->userRepository = $userRepository;
$this->auth0 = $auth0;
}
// ...
}
```
#Hacktoberfest …

Added the Auth0Service as a singleton through the classname

---

src/Auth0/Login/Auth0Service.php

I have changed the visibility of the getter method from private to public. I think this makes a sense because the $auth0 variable is private and its getter is private so there is no ability to get auth0 SDK using Auth0Service. In my case, I need access to the getRefreshToken() method of the SDK because this method was not realized in the service but I need to use the same instance of the SDK which used in methods getUser(), getIdToken().

change the visibility of the getter method from private to public

---

src/Auth0/Login/Auth0UserProvider.php

Return null instead of false from `validateCredentials`, `retrieveByToken` and `retrieveByCredentials`, in Auth0UserProvider.
Because of this function in Illuminate\Auth\GuardHelpers:
```
/**
* Determine if the current user is authenticated.
*
* @return bool
*/
public function check()
{
return ! is_null($this->user());
}
```
This caused issues for us when we migrated to auth0, as some of our users utilized remember_token in previous login system.   
Which caused Auth0UserProvider `retrieveByToken` to be called, and returned `false` user, which laravel counts as a "logged in user". 
Which then caused exception when code asked for $user->stuff on a boolean.
In our case, only `retrieveByToken` was called, but it makes sense to me that `retrieveByCredentials` and `validateCredentials` also …

Return null instead of false in Auth0UserProvider.

---

src/Auth0/Login/Auth0Service.php

This PR fixes the cachehandler to always return null

Fix cachehandler resolving issues

---

src/Auth0/Login/Auth0User.php

Changes `Auth0User::userInfo` and `Auth0User:: accessToken` to protected so extending classes can use the data.
Closes #120

Change private properties to protected

---

composer.json
src/Auth0/Login/Auth0Service.php
src/Auth0/Login/LaravelSessionStore.php
src/Auth0/Login/LoginServiceProvider.php

👋 
This is an implementation of the approach I pitched in https://github.com/auth0/laravel-auth0/issues/125 . Let me know what you think 😄
1. Binded the LaravelSesisonStorage and SessionStateHandler to the container. 
a. I did this so I could re-use it when generating a paswordless `state` token without rebuilding what the SDK already offers for me with the callback handling :)
b. In addition, by binding it on the `StoreInterface` you could now potentially overwrite the driver for this session storage 🎉 
2. Moved some constructor initialisation logic out of the `Auth0Service`
a. Since some dependencies are now bound to the app container. Why not pass them as params? :) 
b. Having less logic in the constructor makes it a bit less error prone and more testable.
- Sadly, I changed the …

Use LaravelSessionStore in the SessionStateHandler.

---

src/Auth0/Login/Auth0JWTUser.php
src/Auth0/Login/Auth0User.php
src/Auth0/Login/LoginServiceProvider.php

Hey again 👋 
I wondered through the code and saw some small changes. Let me know if you agree. I'd be happy to change anything :)
- Replaced `setEnvironment` with `setEnvProperty` since it was marked deprecated in the SDK
- Removed some code from the service provider because I believe it wasn't used. Please challenge me on this if I'm wrong 😄
- Re-aligned some empty return statements for consistency.  
Let's check the integration with a running Laravel application. I

Replace`setEnvironment` with `setEnvProperty`

---

.github/CODEOWNERS
src/Auth0/Login/Auth0Service.php
src/Auth0/Login/LoginServiceProvider.php

Heya,
These are the functional changes extracted from #143 
Instead of binding the SessionStateHandler in the container we are now binding the StateHandler interface. This allows for an easier replacement in case someone wants to.
#143 
[x] This change has been tested on the latest version Laravel
[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

Bind SessionState handler interface in container

---

.circleci/config.yml
.phpcs.xml.dist
composer.json
phpunit.xml.dist
src/Auth0/Login/Auth0Service.php
src/Auth0/Login/LoginServiceProvider.php
tests/Auth0ServiceTest.php

- Fix a bug that did not allow the configuration file values to be used for user store and state handler
- Fix a type hinting bug that did not allow new state handlers to be passed in
- Add a compatibility scan to CI
Closes #154

Allow store and state_handler to be passed in from config

---

src/Auth0/Login/Auth0JWTUser.php
src/Auth0/Login/Auth0User.php
src/Auth0/Login/Contract/Auth0UserRepository.php
src/Auth0/Login/Repository/Auth0UserRepository.php

I fixed wrong typehints in PHPDoc.
[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

Fixed PHPDocs

---

src/Auth0/Login/Auth0JWTUser.php
src/Auth0/Login/Auth0Service.php
src/Auth0/Login/Auth0User.php
src/Auth0/Login/Contract/Auth0UserRepository.php
src/Auth0/Login/Repository/Auth0UserRepository.php
tests/Auth0ServiceTest.php
tests/Unit/Auth0JWTUserTest.php

- **Breaking:** `Auth0JWTUser` and `Auth0User` constructors now require an array
- **Breaking:** `\Auth0\Login\Auth0Service::decodeJWT()` now returns an array
- `Auth0\Login\Contract` now declares param and return types

Use array for Auth0JWTUser and add repo return types

---

src/Auth0/Login/Auth0Service.php
tests/Auth0ServiceTest.php
tests/Unit/Auth0ServiceUnitTest.php

Fixes `decodeJWT` to decode JWT access tokens:
- Uses `IdTokenVerifier` from auth0-php, since Auth0-issued JWTs contain a `sub` claim and this is used by the Laravel user model. 
- Determines the signature verifier to use via the `supported_algs` config; defaults to RS256.
Would like to add additional unit tests, either as a follow-up commit or separate PR. Would be good to use a mock and confirm that the `verify` API is called with the configured options as we'd expect, but the `IdTokenVerifier` class is marked as `final`, so another approach will have to be taken.
[X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
[X] I have read the [Auth0 Code of …

Fix access token validation

---

composer.json

#190 made a change to update `composer.json` to support Laravel 8. A whitespace issue is causing CI to fail, and verified locally when running any `composer` command:
```
[UnexpectedValueException]                                                
Could not parse version constraint ^7.0 : Invalid version string "^7.0 " 
```
#190 
[ ] This change has been tested on the latest version Laravel
[X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
[X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

fix comnposer.json whitespace issue

---

.github/stale.yml

This PR updates stalebot's configuration to [match](https://github.com/auth0/auth0-PHP/pull/474) that of the [PHP SDK repo](https://github.com/auth0/auth0-PHP/blob/master/.github/stale.yml); it will only mark issues as stale that have been labeled "waiting for response."

Only mark stale if waiting for response

---

src/Auth0/Login/Auth0Service.php

Ensure changes made to the user object during the onLogin event hook are stored and propagated for later use, [as suggested here](https://github.com/auth0/laravel-auth0/issues/97#issuecomment-762901400).

[SDK-2318] feat: Store changes made to the user object during the onLogin event hook

---

src/controllers/Auth0Controller.php

In some cases, our Laravel plugin will return null when getUser() is called. We do not currently handle these instances correctly and instead throw an error when we take this null response and attempt to pass it to User::getUserByUserInfo(), which only accepts array values. [Reported here.](https://github.com/auth0/laravel-auth0/issues/198#issuecomment-772999411)

[SDK-2325] fix: Avoid throwing an error when calling getUserByUserInfo() during login callback event when the supplied profile is empty/null

---

CHANGELOG.md
src/Auth0/Login/LoginServiceProvider.php

See the CHANGELOG in this PR or [milestone](https://github.com/auth0/laravel-auth0/milestone/10?closed=1) for details about this release.

Release 6.3.0

---

README.md
composer.json
src/Auth0/Login/Auth0Service.php
src/config/config.php

This PR includes changes for Organizations support, introduced in the Auth0 PHP SDK 7.7.0 release, in the Laravel plugin. It doesn't require any additional tests to be added as the logic is performed by the PHP SDK.
- Updates README to explain Organizations usage
- Bumps Auth0 PHP SDK dependency to 7.7.0 for Organizations hooks
- Exposes handleInvitations() and getInvitationParameters() from the PHP SDK through the Laravel plugin.
- Adds 'organization' option to laravel-auth0 config

[SDK-2375] Add Organizations Support

---

src/Auth0/Login/Auth0Service.php

Pass `api_identifier` config as `audience` to Auth0\SDK\Auth0 as well as adding it to Auth0\Login\Auth0Service::$authConfig with the `audience` key too. 
closes #213 
@evansims 
`App::make('auth0')->login(...)` now includes audience parameter in the link.

Pass `api_identifier` config as `audience` to Auth0\SDK\Auth0

---

src/Auth0/Login/Auth0.php
src/Auth0/Login/Auth0Service.php
src/Auth0/Login/LoginServiceProvider.php

A code changes that relates to Laravel Octane support. Please see change files for more info.
See: https://github.com/auth0/laravel-auth0/issues/212
Recommend to test it in a Laravel Octane server.
When binding `Auth0UserRepository` contract in your `AppServiceProvider`, the second parameter should be a closure returning the concrete class. See example below:
```php
$this->app->bind(
\Auth0\Login\Contract\Auth0UserRepository::class,
function() {
return new \Auth0\Login\Repository\Auth0UserRepository();
}
);
```

Laravel Octane Support

---

README.md

This updates our README to reflect our support of PHP 7.3+ and Laravel 6 or Laravel 8, as Laravel 7 has reached EOL. It adds the same notice about deprecations and supported versions from the auth0-php repo.

Update README for PHP/Lara support cycles

---

src/Auth0/Login/Auth0Service.php

This PR:
- Adds support for the two auth0-php 7.x passwordless API methods, `email_passwordless_start` and `sms_passwordless_start`.
- Adds a `getAuthenticationClass()` class for creating a singleton instance of the `Auth0\SDK\API\Authentication` class.
- Does not introduce new testing due to the simplicity of these alias methods and the presence of existing tests on the parent SDK for these methods. (This plugin will be receiving an overall Q4 which will introduce better testing conditions.)
- Resolves #186 
- Resolves internal ticket SDK-2784
You can run tests locally using a Docker container by issuing `composer run tests` from your shell.

[SDK-2784] Add alias methods for SDK's Passwordless API methods

---

.editorconfig
infection.json.dist
phpinsights.php
phpstan.neon.dist
phpunit.xml.dist
psalm.xml.dist
tests/constants.php

This PR sets up the initial test suite environment's configuration files, for porting the suite over from the Auth0-PHP parent library for use on the Laravel middleware. Does not introduce any new logic changes.

Setup test suite environment

---

.circleci/config.yml
composer.json

This PR includes necessary changes to the Composer package manifest for v7 of the library, to facilitate the upgrade to Auth0-PHP 8 and new test suite conditions, and to point the PSR-4 class autodiscovery to the new class locations. No logic changes are included.
Note: This PR removes support for the now EOL'd PHP 7.3 runtime version, which is not supported by the upstream libraries either. PHP 7.4+ will only be supported in the new v7 major of the library.

Composer package manifest updates

---

config/auth0.php
src/Auth/Guard.php
src/Auth/User/Provider.php
src/Auth0.php
src/Contract/Event/Stateful/TokenExpired.php
src/Contract/Event/Stateful/TokenRefreshFailed.php
src/Contract/Event/Stateful/TokenRefreshSucceeded.php
src/Contract/Http/Middleware/Stateless/Authorize.php
src/Event/Stateful/TokenExpired.php
src/Event/Stateful/TokenRefreshFailed.php
src/Event/Stateful/TokenRefreshSucceeded.php
src/Http/Middleware/Stateful/Authenticate.php
src/Http/Middleware/Stateful/AuthenticateOptional.php
src/Http/Middleware/Stateless/Authorize.php
src/Http/Middleware/Stateless/AuthorizeOptional.php
src/Model/Stateful/User.php
src/Model/Stateless/User.php
src/ServiceProvider.php

This PR adds support for automatically refreshing stateful user sessions when configured with an `offiline_access` scope and a refresh token is present, allowing for extended sessions.
Three other minor adjustments contained that these changes rely on to successfully pass tests:
- The library now self-registers it's router middleware controllers, for less integration effort on the developer's end.
- Adds a 'hasScope' helper to check if a stateless or stateful request has a necessary scope.
- Fixes stateless requests not properly keeping track of the `exp` claim on a access token in the user object.
- Restores `laravel-auth0` telemetry header in API network requests
(This relies on a bugfix in the upstream PHP SDK with a pending release of 8.0.6 to fix a refresh token issue.)

Automatically handle refreshing tokens when a token expires

---

.gitignore
composer.json
config/auth0.php
src/Configuration.php
src/Contract/Configuration.php
src/Http/Controller/Stateful/Callback.php
src/Http/Controller/Stateful/Login.php
src/Http/Controller/Stateful/Logout.php
src/Http/Middleware/Stateful/Authenticate.php

This PR includes three small changes:
- It adds a `Auth0\Laravel\Configuration` class with helper static functions to map the string-based storage format of `.env` files into the property types the Auth0-PHP SDK requires at configuration time; for example a `true` string value into a boolean, and an a space-delimited string to scopes into an array of strings.
- It updates the `config/auth0.php` file to add several common configuration parameters, and updates the format to use the new `Auth0\Laravel\Configuration` class.
- It adds support for `composer.local.json` manifests, to simplify development of the package locally.

Finalize configuration file format

---

CHANGELOG.md

[Full Changelog](https://github.com/auth0/laravel-auth0/compare/6.5.0...7.0.0-BETA1)
Auth0 Laravel SDK v7 includes many significant changes over previous versions:
- Support for Laravel 9.
- Support for Auth0-PHP SDK 8.
- New authentication route controllers for plug-and-play login support.
- Improved authentication middleware for regular web applications.
- New authorization middleware for token-based backend API applications.
As expected with a major release, Auth0 Laravel SDK v7 includes breaking changes. Please review the [upgrade guide](UPGRADE.md) thoroughly to understand the changes required to migrate your application to v7.
**Breaking Changes Summary**
- Namespace has been updated from `Auth0\Login` to `Auth0\Laravel`
- Auth0-PHP SDK dependency updated to V8
- New configuration …

Release 7.0.0-BETA1

---

src/Auth/User/Provider.php

This PR updates `Auth\User\Provider::__construct()` to accept the `Auth0\Laravel\Contract\Auth\User\Repository` interface contract type, rather than the `Auth0\Laravel\Auth\User\Repository` class type itself, to allow custom user providers to be assigned during app configuration.
Closes #256

Update `Auth\User\Provider::__construct()` to accept a Repository Interface, rather than Class

---

README.md

Laravel changed the support lifecycle window and dropped the "LTS" status on Laravel 9 at the last minute before release. [See this tweet for further details.](https://twitter.com/taylorotwell/status/1491834866295525389) Updating our documentation to properly reflect these changes.

Update Requirements in README for Laravel 9

---

src/Http/Controller/Stateful/Logout.php

This PR updates the logout HTTP Controller (`Auth0\Laravel\Http\Controller\Stateful\Logout`) to:
- Redirect the end user back to the host app's index route (`/`) by default, instead of the SDK's callback route
- Allow the return route/url to be configurable by the developer using the `auth0.routes.home` configuration path
Resolves #260

Allow post-logout return url to be configurable

---

CHANGELOG.md

[Full Changelog](https://github.com/auth0/laravel-auth0/compare/6.5.0...7.0.0-BETA2)
Please review the [BETA1 changelog notes below](#700-beta1-2022-02-08) before upgrading your application from 6.x, as 7.0 is a new major containing breaking changes. As with all beta releases, this should not be considered stable or suitable for production use, but your experimentation with and feedback around it is greatly appreciated.
**Changes**
- Update Middleware interface checks for custom user model types [\#263](https://github.com/auth0/laravel-auth0/pull/263) ([sheggi](https://github.com/sheggi))
- Updated UserProvider API [\#264](https://github.com/auth0/laravel-auth0/pull/264) ([evansims](https://github.com/evansims))
- Add Rector to test suite …

Release 7.0.0-BETA2

---

CHANGELOG.md
README.md

Auth0 Laravel SDK v7 includes many significant changes over previous versions:
- Support for Laravel 9.
- Support for Auth0-PHP SDK 8.
- New authentication route controllers for plug-and-play login support.
- Improved authentication middleware for regular web applications.
- New authorization middleware for token-based backend API applications.
As expected with a major release, Auth0 Laravel SDK v7 includes breaking changes. Please review the [upgrade guide](UPGRADE.md) thoroughly to understand the changes required to migrate your application to v7.
**Breaking Changes Summary**
- Namespace has been updated from `Auth0\Login` to `Auth0\Laravel`
- Auth0-PHP SDK dependency updated to V8
- New configuration format
- SDK now self-registers its services and middleware
- New UserProvider API

Release 7.0.0

---

README.md
src/Traits/ActingAsAuth0User.php

as proposed in https://github.com/auth0/laravel-auth0/issues/275, with this PR, a trait is added to support more complex HTTP tests that use routes that are protected by the Auth0 guard and requires the authenticated user to be granted specific scopes.

added ActingAsAuth0User Trait that can be used in HTTP tests

---

src/Http/Controller/Stateful/Callback.php

This PR fixes a bug where `$errorDescription` is incorrectly assigned the value of `$error` instead of `$errorDescription` after an `is_string()` check on the variable type.
Resolves #287

fix: `errorDescription` value incorrectly assigned

---

CHANGELOG.md
src/Auth0.php

[Full Changelog](https://github.com/auth0/laravel-auth0/compare/7.0.0...7.0.1)
**Fixed**
- Fixed an issue in `Auth0\Laravel\Http\Controller\Stateful\Callback` where `$errorDescription`'s value was assigned an incorrect value when an error was encountered. [\#266](https://github.com/auth0/laravel-auth0/pull/288) ([evansims](https://github.com/evansims))
**Closed Issues**
- Resolves [\#287](https://github.com/auth0/laravel-auth0/issues/287) ([piljac1](https://github.com/piljac1))

Release 7.0.1

---

src/Auth/Guard.php
src/Configuration.php
src/Http/Controller/Stateful/Callback.php
src/Http/Controller/Stateful/Login.php
src/Http/Controller/Stateful/Logout.php

This PR:
- Updates our calls to the Laravel `app()` method to reference our own SDK. While the string approach works, there is potential for conflicts if that string gets inadvertently overwritten by the host application. This change ensures we're always referencing the correct class.
- Introduces minor code optimizations to fix linter warnings breaking CI.

change: Use class names for app() calls

---

src/Auth0.php
src/Contract/Auth0.php

This PR updates `Auth0\Laravel\Auth0` and the accompanying interface `Auth0\Laravel\Contract\Auth0` to return interfaces from methods, as opposed to concrete classes, to improve mockability for developers.
Resolves #295
See GitHub results, or run `composer install && vendor\bin\pest` within the cloned project directory on your machine.

[SDK-3576] Return interfaces instead of concrete classes

---

.gitignore
src/Http/Controller/Stateful/Callback.php

This PR resolves an issue for customers using our Laravel SDK with Laravel Octane.
**Bug:** With this combination, upon a user returning to the callback route (`Auth0\Laravel\Http\Controller\Stateful\Callback`) they would be presented with a `Missing Code` error.
**Cause:** The underlying Auth0 PHP SDK fetches the `code` and `state` parameters of the callback using the standard PHP super global `_GET`. This super global is not available when running Laravel under Octane. Within our Laravel SDK, we are (correctly) using Laravel's `Illuminate\Http\Request->query()` method to check for the presence of these values. However, we had not handed these values off directly to the underlying Auth0 PHP SDK, and instead allowed it to attempt to extract them itself from `_GET`, which would fail under …

[SDK-3585] Fix: `Missing Code` error on Callback Route for Octane Customers

---

CHANGELOG.md
src/Auth0.php

**Changed**
- [SDK-3576] Return interfaces instead of concrete classes [\#296](https://github.com/auth0/laravel-auth0/pull/296) ([evansims](https://github.com/evansims))
- Use class names for app() calls [\#291](https://github.com/auth0/laravel-auth0/pull/291) ([evansims](https://github.com/evansims))
**Fixed**
- [SDK-3585] Fix: `Missing Code` error on Callback Route for Octane Customers [\#297](https://github.com/auth0/laravel-auth0/pull/297) ([evansims](https://github.com/evansims))
[SDK-3576]: https://auth0team.atlassian.net/browse/SDK-3576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SDK-3585]: https://auth0team.atlassian.net/browse/SDK-3585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release 7.1.0

---

src/Auth/Guard.php

I've found some third-party apps like Filament use the Auth::viaRemember() when checking auth status
Resolves #

Added viaRemember function to guard

---

CHANGELOG.md
src/Auth0.php

**Changed**
- [SDK-3669] Add StoreInterface bridge for Laravel Sessions [\#307](https://github.com/auth0/laravel-auth0/pull/307) ([evansims](https://github.com/evansims))
- Added viaRemember function to guard [\#306](https://github.com/auth0/laravel-auth0/pull/306) ([tonyfox-disguise](https://github.com/tonyfox-disguise))
[SDK-3669]: https://auth0team.atlassian.net/browse/SDK-3669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release 7.2.0

---

src/Auth0.php

This PR restores the previous (< 7.2.0) and intended behavior of only requiring a session configuration when an appropriate stateful strategy is configured by the host application.
Resolves #314

[SDK-3716] Do not require session configuration for stateless strategies

---

composer.json

This PR pins the `psr/cache` dependency (the standard interface spec for [PSR-6](https://www.php-fig.org/psr/psr-6/) to its PHP 8.0-targeted iteration, `^3.0`.
This dependency was previously implicitly required through the Auth0-PHP SDK, but because of our 7.4 support there, this allowed `^1.0 || ^2.0 || ^3.0`, which is no longer compatible downstream with this library.
Resolves #315

[SDK-3715] Pin `psr/cache` dependency version

---

CHANGELOG.md
src/Auth0.php

[Full Changelog](https://github.com/auth0/laravel-auth0/compare/7.2.0...7.2.1)
**Fixed**
- `Auth0\Laravel\Auth0` no longer requires a session configuration for stateless strategies, restoring previous behavior. [\#317](https://github.com/auth0/laravel-auth0/pull/317) ([evansims](https://github.com/evansims))
- The SDK now requires `^3.0` of the `psr/cache` dependency, to accomodate breaking changes made in the upstream interface (typed parameters and return types) for PHP 8.0+. [\#316](https://github.com/auth0/laravel-auth0/pull/316) ([evansims](https://github.com/evansims))

Release 7.2.1

---

composer.json

This PR bumps the minimum supported `auth0/auth0-php` dependency version installed from `^8.0` to `^8.3.2`, which includes some important fixes specifically for the Laravel package under PHP 8.0+.
See internal ticket SDK-3721.
Please see GitHub status checks, or run `composer test` from a local clone of the project directory.

[SDK-3721] Bump minimum `auth0/auth0-php` version to `^8.3.2`

---

CHANGELOG.md
src/Auth0.php

**Fixed**
- [SDK-3720] Restore `php artisan vendor:publish` command [\#321](https://github.com/auth0/laravel-auth0/pull/321) ([evansims](https://github.com/evansims))
- [SDK-3721] Bump minimum `auth0/auth0-php` version to `^8.3.4` [\#322](https://github.com/auth0/laravel-auth0/pull/322) ([evansims](https://github.com/evansims))
[SDK-3720]: https://auth0team.atlassian.net/browse/SDK-3720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SDK-3721]: https://auth0team.atlassian.net/browse/SDK-3721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release 7.2.2

---

src/Cache/LaravelCachePool.php

Even when there is a value in the cache, it was still returning a miss, which made the caching practically unusable...

fix: Auth0\Laravel\Cache\LaravelCachePool::createItem returning a cache miss

---

src/Auth/Guard.php
src/Contract/Event/Stateless/TokenVerificationAttempting.php
src/Contract/Event/Stateless/TokenVerificationFailed.php
src/Contract/Event/Stateless/TokenVerificationSucceeded.php
src/Event/Stateful/AuthenticationSucceeded.php
src/Event/Stateless/TokenVerificationAttempting.php
src/Event/Stateless/TokenVerificationFailed.php
src/Event/Stateless/TokenVerificationSucceeded.php
src/Http/Controller/Stateful/Callback.php

This PR includes enhancements requested by [nickescobedo](https://github.com/nickescobedo) in #328 to raise additional [Laravel authentication events](https://laravel.com/docs/9.x/authentication#events). This should improve interoperability with other Laravel packages that interact with the authentication layer.
I've added the following Laravel auth events:
- `Illuminate\Auth\Events\Attempting`
- `Illuminate\Auth\Events\Validated`
- `Illuminate\Auth\Events\Failed`
- `Illuminate\Auth\Events\Login`
- `Illuminate\Auth\Events\Authenticated`
- `Illuminate\Auth\Events\Logout`
I've also added a few new SDK events for stateless token verification events:
- `Auth0\Laravel\Event\Stateless\TokenVerificationAttempting`
- `Auth0\Laravel\Event\Stateless\TokenVerificationFailed`
- …

add: Raise additional Laravel Auth Events

---

config/auth0.php

This PR resolves an issue reported by @affektde in #330 in which the `env()` helper method returns the `AUTH0_COOKIE_EXPIRES` value as a `string`, but the underlying PHP SDK expects an `int`.
This also fixes the environment variable mistakenly referenced as `COOKIE_EXPIRES` rather than `AUTH0_COOKIE_EXPIRES`.
Resolves #330 
Use `composer test` in a locally cloned repo, or review the GitHub status checks below.

fix: `env()` incorrectly assigns `cookieExpires` to a `string` value

---

CHANGELOG.md
src/Auth0.php

**Added**
- add: Raise additional Laravel Auth Events [\#331](https://github.com/auth0/laravel-auth0/pull/331) ([evansims](https://github.com/evansims))
**Fixed**
- fix: `env()` incorrectly assigns `cookieExpires` to a `string` value [\#332](https://github.com/auth0/laravel-auth0/pull/332) ([evansims](https://github.com/evansims))
- fix: Auth0\Laravel\Cache\LaravelCachePool::createItem returning a cache miss [\#329](https://github.com/auth0/laravel-auth0/pull/329) ([pkivits-litebit](https://github.com/pkivits-litebit))

Release 7.3.0

---

src/Auth0.php
src/Contract/Event/Configuration/Building.php
src/Event/Configuration/Building.php
src/Store/LaravelSession.php

This PR adds a `Auth0\Laravel\Event\Configuration\Building` event, which allows host applications to listen for and hook into the SDK's configuration build process. This allows developers to dynamically alter their configuration for their needs at run time.
First part of resolution for #336

feat: Add `Auth0\Laravel\Event\Configuration\Building` event hook

---

.github/ISSUE_TEMPLATE/Bug Report.yml
CHANGELOG.md
src/Auth0.php

**Added**
-   Support for Laravel 10 [#349](https://github.com/auth0/laravel-auth0/pull/349)
-   New `Auth0\Laravel\Traits\Imposter` trait to allow for easier testing. [Example usage](./tests/Unit/Traits/ImpersonateTest.php)
-   New Exception types have been added for more precise error catching.
**Changed**
The following changes have no effect on the external API of this package, but may affect internal usage.
-   `Guard` will now more reliably detect changes in the underlying Auth0-PHP SDK session state.
-   `Guard` will now more reliably sync changes back to the underlying Auth0-PHP SDK session state.
-   `Guard` now inherits the `DeferrableProvider` interface to better support Laravel's deferred provider loading.
-   `StateInstance` concept has been replaced by new `Credentials` …

release: 7.5.0

---

CHANGELOG.md
src/Auth0.php

**Fixed**
-   Relaxed response types from middleware to use low-level `Symfony\Component\HttpFoundation\Response` class, allowing for broader and custom response types.

Release 7.5.2

---

src/Auth/Guard.php

This PR addresses a bug where `legacyGuardUserMethod` behaviour mistakenly consumes `$token` instead of `$session` for automatic logins during `user()` calls.
Resolves #363 
Tests are passing. No additions were necessary to cover this change.

fix: legacyGuardUserMethod should use `$session` not `$token`

---

src/Http/Middleware/Stateful/Authenticate.php
tests/Unit/Http/Middleware/Stateful/AuthenticateTest.php

This PR updates the `Auth0\Laravel\Http\Middleware\Stateful\Authenticate` route middleware to `setIntendedUrl()` from an intercepted request before issuing the redirect to the login route.
The callback route was already configured to issue redirects after login that default to honouring any assigned intended URLs, so no other changes are necessary elsewhere.
To illustrate this process:
- Visitor requests `/protected-route`.
- `auth0.authorize` middleware determines visitor is not authenticated.
- `auth0.authorize` makes note that the visitor was trying to access `/protected-route`.
- `auth0.authorize` redirects to `/login` to kick off the authentication flow.
- Visitor completes the authentication flow, and is dropped back off to `/callback`.
- `Auth0\Laravel\Http\Controller\Stateful` …

feature: Auth middleware will now setIntendedUrl() before login redirect

---

.github/ISSUE_TEMPLATE/Bug Report.yml
CHANGELOG.md
src/Auth0.php

-   `Auth0\Laravel\Http\Middleware\Guard`, new middleware that forces Laravel to route requests through a group using a specific Guard. ([\#362](https://github.com/auth0/laravel-auth0/pull/362))
-   `Auth0\Laravel\Http\Middleware\Stateful\Authenticate` now remembers the intended route (using `redirect()->setIntendedUrl()`) before kicking off authentication flow redirect. Users will be returned to the memorized intended route after completing their authentication flow. ([\#364](https://github.com/auth0/laravel-auth0/pull/364))
-   legacyGuardUserMethod behavior should use `$session`, not `$token` ([\#353](https://github.com/auth0/laravel-auth0/pull/365))

Release 7.6.0

---

src/Auth/Guard.php
src/Contract/Auth/Guard.php
tests/Unit/Auth/GuardStatefulTest.php

This PR adds a `refreshUser()` method to the SDK's Guard API; it wraps up calling the `/userinfo` endpoint to retrieve updated data for the authenticated user. This is intended as a convenience helper to reflect changes issued to the Management API without requiring a user to re-authenticate.
Usage:
```php
<?PHP
$sdk = app('auth0');
$guard = app('auth0.guard');
$guard->setUser('auth0|...');
echo $guard->user()->name; // John Doe
$sdk->management()->users()->update(
user: $guard->user()->getAuthIdentifier(), 
body: [
'name' => 'Jane Doe'
]
);
$guard->refreshUser();
echo $guard->user()->name; // Jane Doe
```
Jira: SDK-4148
- Tests have been added to cover this new method.

feature: Add `refreshUser()` method to Guard

---

.github/ISSUE_TEMPLATE/Bug Report.yml
CHANGELOG.md
src/Auth0.php

-   `Auth0\Laravel\Auth0` now has a `management()` shortcut method for issuing Management API calls. ([\#376](https://github.com/auth0/laravel-auth0/pull/376))
-   `Auth0\Laravel\Auth0\Guard` now has a `refreshUser()` method for querying `/userinfo` endpoint and refreshing the authenticated user's cached profile data. ([\#375](https://github.com/auth0/laravel-auth0/pull/375))
-   `Auth0\Laravel\Http\Controller\Stateful\Login` now raises a `LoginAttempting` event, offering an opportunity to customize the authorization parameters before the login redirect is issued. ([\#382](https://github.com/auth0/laravel-auth0/pull/382))
-   The `tokenCache`, `managementTokenCache`, `sessionStorage` and `transientStorage` configuration values now support `false` or `string` values pointing to class names …

Release 7.7.0

---

.github/workflows/php_phpstan.yml
src/Auth0.php
tests/Unit/Auth0Test.php

This PR refactors the configuration building step, which is responsible for reshaping the Laravel configuration array into a format consumable by the underlying PHP SDK.
This PR also includes new configuration options for the `tokenCache`, `managementTokenCache`, `sessionStorage`, and `transientStorage` properties.
These now accept a `false` boolean value to disable those features:
```php
<?php // config/auth0.php
declare(strict_types=1);
use Auth0\Laravel\Configuration;
use Auth0\SDK\Configuration\SdkConfiguration;
return [
// Disables sessions (still defaults to SDK's `LaravelSessionStore`)
'sessionStorage' => false
];
```
These properties also now accept string values, either a class name (`\Some\Cache::class`) or alias (`cache.psr6`) for the SDK to instantiate a given class at …

Expand Configuration Properties (and Refactor Config Builder)

---

docs/Events.md
src/Contract/Event/Stateful/LoginAttempting.php
src/Event/Stateful/LoginAttempting.php
src/Http/Controller/Stateful/Login.php

This PR implements a feature request by @elliottlawson to allow for easier customization of authorization parameters before a login redirect is issued.
This is implemented through a new event, `Auth0\Laravel\Event\Stateful\LoginAttempting`. Applications can hook into this event and use the `setParameters()` method of the event to define additional parameters to be issued with the login redirect.
Example usage:
```php
<?php // app/Listeners/CustomLoginParameters.php
namespace App\Listeners;
use Auth0\Laravel\Event\Stateful\LoginAttempting;
final class CustomLoginParameters
{
public function handle(LoginAttempting $event): void
{
$event->setParameters([
'connection' => '...',
]);
}
}
```
```php
<?php // app/Providers/EventServiceProvider.php
use Auth0\Laravel\Event\Stateful\LoginAttempting; …
```

Add `LoginAttempting` event for customizing authorization parameters

---

src/Configuration.php

This resolves an issue with parsing `.env` files that contain lines without standard key-value strings, such as `# Comments`.
Resolves #394

Fix: Exception when parsing `.env` with comments

---

docs/Configuration.md

The classes in the documentation for the manual configuration was not up to date with the latest release. The namespaces and the aliases in the configuration readme has been updated with the correct values.

Update namespaces and aliases for classes in the configuration documentation 

---

composer.json
rector.php

This PR updates the continuous integration's Rector rulset to support the 0.17 release. It adds new rules, removes deprecated rules, and removes several problematic rules that were occasionally causing CI jobs to lock up.
(Rector is a code quality analysis and refactoring tool for PHP.)
- https://github.com/rectorphp/rector/releases/tag/0.17.0
See CI results.

ci: Update Rector ruleset to 0.17

---

src/Configuration.php

This PR resolves an issue where quote characters (`'`, or `"`) are not removed from strings when pulling values from `dotenv` files. Although these quotes are always optional, it is common practice to use them. This was previous behavior before the 7.7 configuration system improvements.
Closes #399 
Testing remains at 100%.

[SDK-4337] fix: Trim quote characters from around environment variable strings

---

src/Configuration.php

This PR restore previous host environment variable configurations, in addition to the "dotenv" and JSON-based configuration methods.
Closes #405 
Test coverage remains at 100%.

[SDK-4337] fix: Restore host environment variable processing

---

config/auth0.php
src/Configuration.php

This PR adds an optional `configurationPath` setting to the `config/auth0.php` SDK configuration file for applications, which allows developers to specify the search path the SDK will use to search for configuration files (.auth0.*.json, .env*).
Closes #397 
Test coverage remains at 100%.

[SDK-4337] feat: Add setting to define search path for configuration files

---

src/Guards/GuardAbstract.php

This PR updates `Auth0\Laravel\Guards\GuardAbstract` abstract class (which is extended by the concrete `Auth0\Laravel\Guards\AuthenticationGuard` and `Auth0\Laravel\Guards\AuthorizationGuard` classes) to extend the `Illuminate\Contracts\Auth\Guard` interface. This is a framework interface provided by Laravel.
No functional changes related to this change, but extending it is suggested as a best practice.
Addresses feedback from @devfrey in #385.
Test coverage remains at 100%.

[SDK-4338] feat: `GuardAbstract` extends `Illuminate\Contracts\Auth\Guard`

---

CHANGELOG.md
src/ServiceAbstract.php

-   SDK configuration (`config/auth0.php`) now supports a `configurationPath` property for specifying a custom search path for `.auth0.*.json` and `.env*` files. ([\#407](https://github.com/auth0/laravel-auth0/pull/407))
-   `Auth0\Laravel\Guards\GuardAbstract` now extends `Illuminate\Contracts\Auth\Guard`. ([\#410](https://github.com/auth0/laravel-auth0/pull/410))
-   Resolved host environment variables not being loaded as expected when a `.env` file is also used. ([\#408](https://github.com/auth0/laravel-auth0/pull/408))
-   Resolved surrounding quote characters not being trimmed from environment variables and `.env` files during processing. ([\#409](https://github.com/auth0/laravel-auth0/pull/409))

Release 7.9.0

---

src/Middleware/GuardMiddleware.php
src/ServiceProviderAbstract.php

This PR removes a redundant middleware insertion call that in some circumstances could cause the session-based authentication guard to be invoked during stateless/token-based authorization requests.

fix: Remove redundant middleware insertion

---

src/Configuration.php
tests/Unit/ConfigurationTest.php

This PR fixes an issue where, out of the box, the Laravel QS does not properly have the placeholder dotenv values ignored when a JSON configuration is used, resulting in validation errors, as environment variables always take priority.
-   [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
-   [ ] I have read the [Auth0 code of conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

fix: Ignore default AUTH0_ dotenv values

---

src/ServiceProviderAbstract.php

This PR updates the guard middleware registration process to prepend the SDK's guards to the MiddlewarePriority manifest, ensuring they are loaded before `Illuminate\Auth\Middleware\Authenticate`.
`Illuminate\Auth\Middleware\Authenticate` is automatically registered as a priority middleware by Laravel by default. This class includes a `authenticate()` method, which can cause issues (e.g. infinite loops, etc.) when it incorrectly determines a guard is not available.
-   [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
-   [ ] I have read the [Auth0 code of conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

fix: Inject Guards into MiddlewarePriority manifest

---

src/Bridges/CacheBridgeAbstract.php
tests/Unit/Bridges/CacheBridgeTest.php

This PR updates cache save value. 
According to the Auth0\Laravel\Bridges\CacheItemBridgeAbstract::get(), the item value always returns null because `isHit()` is false til the value is cached, and as a result, the cache is not working properly.
```php
final public function get(): mixed
{
return $this->isHit() ? $this->value : null;
}
``` 
So for cache save function, we need to use `getRawValue(),` which is not dependent on hit status.

fix: `CacheBridgeAbstract::save()` not assigning value to cache when cache hit mises

---

composer.json
config/auth0.php
docs/BackchannelLogout.md
docs/Configuration.md
src/Configuration.php
src/Entities/InstanceEntityAbstract.php
tests/Unit/ServiceTest.php

This PR implements support for Back-Channel Logout.
See internal ticket SDK-4732.
Tests have been updated to add coverage for these new features.

feat(SDK-4732): Implement support for Back-Channel Logout

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
docs/Installation.md
src/ServiceAbstract.php

**Added**
- Implement support for Back-Channel Logout [\#435](https://github.com/auth0/laravel-auth0/pull/435) ([evansims](https://github.com/evansims))
- Restore configurable route paths [\#436](https://github.com/auth0/laravel-auth0/pull/436) ([evansims](https://github.com/evansims))
**Fixed**
- Resolve `CacheBridgeAbstract::save()` not storing values when cache misses [\#434](https://github.com/auth0/laravel-auth0/pull/434) ([seruymt](https://github.com/seruymt))

Release 7.12.0

---

composer.json

It's ready for Laravel 11
Use official psalm-laravel-plugin
no

Use official psalm-laravel-plugin

---

src/Guards/AuthenticationGuard.php

The code currently performs full credential refreshes several times per request, which has a negative performance impact, especially when complex queries are involved. This change updates the SDK to refresh the credential once per request, and serve up a cached version of the credential for subsequent calls to getCredential within the same request thereafter.
Please see associated issue for more detailed information.
https://github.com/auth0/laravel-auth0/issues/452
-   [X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
-   [X] I have read the [Auth0 code of conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

perf: Update getCredential to only refresh credential once per request

---

composer.json

Laravel 12 Support
