auth0/laravel-auth0

src/Auth0/Login/Auth0Service.php, src/Auth0/Login/Auth0User.php
The access token is not part of the "user info".
=> Fixed the way the access token is pased to the A0User

examples/laravel-api/composer.json
fix https://github.com/auth0/laravel-auth0/issues/26
=> update auth0/login dependency in example

src/Auth0/Login/Auth0Service.php
See https://github.com/auth0/auth0-PHP/blob/master/src/JWTVerifier.php#L51-L57
=> Fixing JWTVerifier

src/config/config.php
When set, you get "array to string conversion" [here](https://github.com/auth0/laravel-auth0/blob/master/src/Auth0/Login/Auth0Service.php#L101)
=> Fixing config type

src/Auth0/Login/Auth0Service.php
References #53 without the authentication refactor. Was not needed in my testing.
=> Adding accessor to retrieve JWT from Auth0Service

README.md, src/Auth0/Login/Auth0User.php
=> Use  instead of  to identify the Auth0 user 

composer.json
This will make the package work with [auto-discovery](https://github.com/laravel/framework/pull/19420) in Laravel 5.5.
Remember that you need to :label: a new version of the package after merging this!
=> AutoDiscovery

CHANGELOG.md, README.md, composer.json, src/Auth0/Login/Auth0Service.php, src/config/config.php, src/controllers/Auth0Controller.php
**Closed issues**
- pls change config arg name [\#95](https://github.com/auth0/laravel-auth0/issues/95) ([ekadesign](https://github.com/ekadesign))
**Added**
- AutoDiscovery [\#91](https://github.com/auth0/laravel-auth0/pull/91) ([m1guelpf](https://github.com/m1guelpf))
- Added guzzle options to config to allow for connection options [\#88](https://github.com/auth0/laravel-auth0/pull/88) ([mjmgooch](https://github.com/mjmgooch))
**Changed**
- Change default settings file [\#96](https://github.com/auth0/laravel-auth0/pull/96) ([joshcanhelp](https://github.com/joshcanhelp))
- Utilise Auth0->Login to ensure state validation [\#90](https://github.com/auth0/laravel-auth0/pull/90) ([cocojoe](https://github.com/cocojoe))
**Fixed**
- Make code comments gender neutral …
=> Release 5.1.0

examples/README.md
Fixed typo and added some links following other auth0 projects.
=> Fixed typo

composer.json
=> Updated required PHP version to 5.4 in composer

README.md, composer.json
Updated readme and composer.json to indicate compatibility with Laravel 6. No source-code changes.
- https://github.com/auth0/laravel-auth0/issues/138
- https://laravel.com/docs/6.0/upgrade
=> Support Laravel 6

CHANGELOG.md, src/Auth0/Login/LoginServiceProvider.php
See [milestone](https://github.com/auth0/laravel-auth0/issues?q=is%3Aclosed+milestone%3A5.3.0) or CHANGELOG below for fixes and additions.
=> Release 5.3.0

.circleci/config.yml, .gitignore, composer.json, phpunit.xml.dist, tests/Unit/Auth0JWTUserTest.php
Cherry picked the backwards compatible changes from #143
#143 
1. Checkout branch
1. Run `composer update`
1. Run `./vendor/bin/phpunit`
1. Acknowledge that tests ran :)
[x] This change has been tested on the latest version Laravel
[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
=> Setup PHPUnit testing suite

src/config/config.php
Auth0 SDK supports also 'persist_refresh_token' configuration, key is missing on laravel-auth0 configuration file, will be handy to have the key there.
=> Add 'persist_refresh_token' key to laravel-auth0 configuration file.

CHANGELOG.md, examples/README.md, src/Auth0/Login/LoginServiceProvider.php
See CHANGELOG or [Milestone](https://github.com/auth0/laravel-auth0/issues?q=is%3Aclosed+milestone%3A5.3.1) for changes in this release.
=> Changelog and SDK version for 5.3.1 release

.circleci/config.yml, .github/stale.yml, .gitignore, .phpcs.xml.dist, CHANGELOG.md, composer.json, examples/README.md, phpunit.xml.dist, src/Auth0/Login/Auth0Service.php, src/Auth0/Login/LoginServiceProvider.php, src/config/config.php, tests/Auth0ServiceTest.php, tests/Unit/Auth0JWTUserTest.php
Everything here was approved in one form or another when merged into the `master` branch.
=> Merge changes from master

CHANGELOG.md, README.md, src/Auth0/Login/LoginServiceProvider.php
See Changelog below for changes included.
=> Releasing 5.4.0

composer.json
Applying Laravel 7 support to v7 branch. Original PR here: https://github.com/auth0/laravel-auth0/pull/167
https://github.com/auth0/laravel-auth0/pull/167
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 
[X] This change has been tested on the latest version Laravel
[X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
[X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
=> laravel 7 support

CHANGELOG.md, README.md, composer.json, src/Auth0/Login/Auth0JWTUser.php, src/Auth0/Login/Auth0User.php, src/Auth0/Login/LoginServiceProvider.php
Please see the changelog below or [milestone](https://github.com/auth0/laravel-auth0/issues?q=milestone%3A6.0.0+is%3Aclosed) for more information about this release.
=> Release 6.0.0

.circleci/config.yml
Names the report uploaded by snyk so that it doesn't show up with a default name.
https://snyk.io/blog/snyk-cli-cheat-sheet/
[ ] This change has been tested on the latest version Laravel
[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
=> Update Snyk reported name

CHANGELOG.md, README.md, composer.json, src/Auth0/Login/LoginServiceProvider.php
See the `CHANGELOG` below or the [milestone](https://github.com/auth0/laravel-auth0/milestone/7) for details about the release.
=> Release 6.0.1

CHANGELOG.md, src/Auth0/Login/LoginServiceProvider.php
Release version 6.1.0. See [CHANGELOG](https://github.com/auth0/laravel-auth0/pull/193/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e) for changes included in this release.
Resolves https://github.com/auth0/laravel-auth0/issues/188
[X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
[X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
=> Release 6.1.0

composer.json
This PR will address Composer V2 installation errors (currently causing CircleCI to fail the repos tests.)
=> SDK-2102 Fix Composer V2 installation errors

CHANGELOG.md, src/Auth0/Login/LoginServiceProvider.php
See the [CHANGELOG](CHANGELOG.md) in this PR or [milestone](https://github.com/auth0/laravel-auth0/milestone/11?closed=1) for details about this release.
=> Release 6.4.0

LICENSE.txt, README.md, UPGRADE.md
This PR includes:
- README.md:
- Updated to cover changes to the installation, configuration and integration of the Laravel SDK.
- Expanded usage guidance.
- Note that some documentation links will not work [until this PR is merged](https://github.com/auth0/docs/pull/9994) on release day.
- UPGRADE.md
- New document offering migration advice and a summary of breaking changes for developers upgrading from v6 to v7 BETA1.
- LICENSE.txt
- Updated to reflect current year.
=> v7 Beta Documentation: Update README.md / add UPGRADE.md

.circleci/config.yml, composer.json, rector.php, src/Configuration.php, src/ServiceProvider.php
This PR adds Rector to the CircleCI and Composer `run tests` suites. Rector is a code quality analysis too that will make analyze source code structure, and make suggestions for improvements in areas it identifies.
Use `composer run tests`, `composer run tests:rector` or review the CircleCI logs.
=> Introduce Rector tests for code quality improvement suggestions

src/Model/User.php, src/StateInstance.php
This PR applies code improvements suggested by the addition of Rector to the test suite.
=> Apply Rector improvements

src/controllers/Auth0Controller.php
Replace the usage of global aliases with facades.
Resolves #277
=> use facades instead of aliases

README.md
This PR fixes [a typo identified](https://github.com/auth0/laravel-auth0/issues/334) by @joshelboy around the artisan `vendor:publish` command usage.
Resolves #334
Documentation change; none necessary
=> fix: Typo in README vendor:publish command

CHANGELOG.md, src/Auth0.php
**Added**
- feat: Add `Auth0\Laravel\Event\Middleware\...` event hooks [\#340](https://github.com/auth0/laravel-auth0/pull/340) ([evansims](https://github.com/evansims))
- feat: Add `Auth0\Laravel\Event\Configuration\Building` event hook [\#339](https://github.com/auth0/laravel-auth0/pull/339) ([evansims](https://github.com/evansims))
=> Release 7.4.0

README.md
This PR adds a note about the `StartSession` middleware being a requirement in the README, with a portion added to the setup guide to check to ensure it is enabled (which it is by default.)
Resolves #342
=> docs: Add note about `StartSession` middleware

composer.json
Update composer.json to support Laravel v10
None
Resolves #
No code is added, I only runed the original tests and got pass
- [v] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [v] I have read the [Auth0 code of conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
=> add Laravel v10 support

CHANGELOG.md, src/Auth0.php
**Fixed**
-   Resolved an issue wherein custom user repositories could fail to be instantiated under certain circumstances.
=> release: 7.5.1

docs/Management API.md
This PR adds reference documentation for using the Management API with the Laravel SDK as a new file, `docs/Management API.md`.
Jira: SDK-4150
N/A
=> documentation: Add Management API reference doc

docs/User Models and Repositories.md
This PR adds reference documentation for creating custom user models and repositories for use with the Laravel SDK as a new file, `docs/User Models and Repositories.md`.
Jira: SDK-4150
N/A
=> documentation: Add User Models and Repositories reference doc

tests/Unit/Guards/AuthenticationGuardTest.php
Issue:
The `find()` method is mentioned in the test, however, is not tested. This may have been an oversight and would be useful to document the use case of the `->find()` method. 
- Include testing of the find() method
- Update test titles to emphasize find() method testing
- Validate results of the find() method using appropriate expectations and assertions
N/A
Updates test
-   [✅] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
-   [✅ ] I have read the [Auth0 code of conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
=> Refactor unit tests to include testing the find() method

docs/Configuration.md
Documentation is missing a square bracket
n/a
n/a
=>  Add missing square bracket in route registration example

.github/workflows/semgrep.yml, .github/workflows/snyk.yml, .github/workflows/tests.yml
-   [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
-   [ ] I have read the [Auth0 code of conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
=> Changed pull_request_target to pull_request

composer.json, src/Bridges/SessionBridgeAbstract.php, src/EventsContract.php, src/Guards/AuthorizationGuard.php, src/Guards/GuardAbstract.php, src/UserProviderAbstract.php
Fixes failing tests so other PRs can be merged.
- Added missing type hinting
- Added missing spatie/laravel-ray as dev dependency
PR #459 
PR #470 
=> refactor: fix failing tests
